### ISSUE TITLE
torch.load generates error

### ISSUE THREAD

**Issue by yesufeng** [catalina17/VideoNavQA#6]
https://github.com/catalina17/VideoNavQA/blob/69d4a21491e653afe5fb5cda21c7d759c3653b6a/eval/utils.py#L49

I have encountered an error when calling get_object_detector() from q_and_v_eval.py. I have downloaded the data tar and the OBJ_DETECTOR_PATH is set correctly to the obj_detect.pt path in the utils.py, the error message is the below, any suggestion?

Traceback (most recent call last):
  File "/home/yesu/projects/VideoNavQA/videonavqa/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/yesu/projects/VideoNavQA/videonavqa/lib/python3.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 2: ordinal not in range(128)

**Comment by catalina17** [comment]
Can you try loading it in python2 instead? Alternatively, there are some
fixes suggested here:

https://stackoverflow.com/questions/10406135/unicodedecodeerror-ascii-codec-cant-decode-byte-0xd1-in-position-2-ordinal/40346898

I'll look into it and get back to you.

**Comment by catalina17** [comment]
Ok, looked into this and converted the dict from `python2` to `python3`, please see the README for details!
